## hello_sp.py

In [13]:
"""空間プーラーの動作を示す簡単なプログラム"""

import numpy as np
import random
from nupic.bindings.algorithms import SpatialPooler as SP



uintType = "uint32"

In [14]:
class Example(object):
  """コードを保持するクラス

  TODO: このクラスを削除してください。
  コードを入力してください。
  """


  def __init__(self, inputDimensions, columnDimensions):
    """
     パラメータ:
     ----------
     _inputDimensions: 入力のサイズ。(m,n) はサイズ m x n を与えます。
     _columnDimensions:列の2次元配列のサイズ
     """
    self.inputDimensions = inputDimensions
    self.columnDimensions = columnDimensions
    self.inputSize = np.array(inputDimensions).prod()
    self.columnNumber = np.array(columnDimensions).prod()
    self.inputArray = np.zeros(self.inputSize, dtype=uintType)
    self.activeArray = np.zeros(self.columnNumber, dtype=uintType)

    random.seed(1)

    self.sp = SP(self.inputDimensions,
                 self.columnDimensions,
                 potentialRadius = self.inputSize,
                 numActiveColumnsPerInhArea = int(0.02*self.columnNumber),
                 globalInhibition = True,
                 seed = 1,
                 synPermActiveInc = 0.01,
                 synPermInactiveDec = 0.008)


  def createInput(self):
    """ランダム入力vectorを作成する"""

    print "-" * 70 + "ランダム入力vectorの作成" + "-" * 70

    #clear the inputArray to zero before creating a new input vector
    self.inputArray[0:] = 0

    for i in range(self.inputSize):
      #randrange returns 0 or 1
      self.inputArray[i] = random.randrange(2)


  def run(self):
    """入力vectorで空間プーラーを実行します"""

    print "-" * 80 + "SDRの計算" + "-" * 80

    #activeArray[column]=1 if column is active after spatial pooling
    self.sp.compute(self.inputArray, True, self.activeArray)

    print self.activeArray.nonzero()


  def addNoise(self, noiseLevel):
    """入力ビットの10%の値を反転させる（ノイズを加える)

        :param noiseLevel. 反転させる総入力ビット数の割合．
    """

    for _ in range(int(noiseLevel * self.inputSize)):
      # 0.1*self.inputSize represents 10% of the total input bits
      # random.random() returns a float between 0 and 1
      randomPosition = int(random.random() * self.inputSize)

      # Flipping the bit at the randomly picked position
      if self.inputArray[randomPosition] == 1:
        self.inputArray[randomPosition] = 0

      else:
        self.inputArray[randomPosition] = 1

      # Uncomment the following line to know which positions had been flipped.
      # print "The value at " + str(randomPosition) + " has been flipped"

example = Example((32, 32), (64, 64))

In [15]:
# Lesson 1
print "\n \n以下のカラムはSDRを表しています"
print "入力をランダムにするので、毎回異なるカラムのセット"
print "レッスン - 入力vectorが異なるとSDRが異なります\n\n"

# Trying random vectors
for i in range(3):
  example.createInput()
  example.run()


 
以下のカラムはSDRを表しています
入力をランダムにするので、毎回異なるカラムのセット
レッスン - 入力vectorが異なるとSDRが異なります


----------------------------------------------------------------------ランダム入力vectorの作成----------------------------------------------------------------------
--------------------------------------------------------------------------------SDRの計算--------------------------------------------------------------------------------
(array([   7,   61,  128,  129,  232,  291,  347,  367,  458,  466,  539,
        592,  599,  727,  762,  780,  817, 1022, 1066, 1167, 1172, 1420,
       1466, 1484, 1498, 1507, 1518, 1531, 1636, 1700, 1716, 1811, 1836,
       1875, 2026, 2033, 2157, 2212, 2233, 2262, 2292, 2374, 2390, 2494,
       2522, 2527, 2624, 2663, 2701, 2722, 2754, 2766, 2791, 2799, 2810,
       2816, 2821, 2822, 2828, 2859, 2861, 2875, 2877, 3049, 3066, 3067,
       3074, 3084, 3120, 3402, 3438, 3486, 3515, 3579, 3690, 3791, 3816,
       3900, 3946, 3957, 4092]),)
----------------------------------------------------

In [5]:
# Lesson 2
print "\n\n同一の入力を与えるため、同一のSDR"
print "レッスン - 同一入力で同一SDRが得られる\n\n"

print "-" * 75 + "同一入力vectorの使用" + "-" * 75

# Trying identical vectors
for i in range(2):
  example.run()



Identical SDRs because we give identical inputs
Lesson - identical inputs give identical SDRs


---------------------------------------------------------------------------Using identical input vectors---------------------------------------------------------------------------
--------------------------------------------------------------------------------Computing the SDR--------------------------------------------------------------------------------
(array([  34,   81,  129,  158,  165,  195,  278,  289,  315,  347,  448,
        481,  780,  817, 1014, 1019, 1022, 1098, 1123, 1164, 1285, 1361,
       1518, 1583, 1690, 1693, 1700, 1716, 1734, 1877, 1931, 2006, 2009,
       2026, 2033, 2049, 2075, 2095, 2105, 2111, 2157, 2224, 2374, 2384,
       2494, 2560, 2568, 2613, 2620, 2622, 2624, 2723, 2766, 2791, 2799,
       2838, 2850, 2859, 2861, 2897, 3005, 3066, 3074, 3120, 3197, 3236,
       3412, 3432, 3459, 3469, 3492, 3564, 3590, 3621, 3685, 3748, 3869,
       3920, 3921, 3955, 4092]),

In [12]:
# Lesson 3
print "\n\n今は入力vectorを少し変えています"
print "1を0に、0を1に少しずつ変えていきます"
print "結果として得られるSDRは、元のSDRと類似していますが、同一ではありません"
print "レッスン - 入力vectorが似ているとSDRが似てくる\n\n"

# Adding 10% noise to the input vector
# Notice how the output SDR hardly changes at all
print "-" * 75 + "入力vectorに10%のノイズを加えた後" + "-" * 75
example.addNoise(0.1)
example.run()

# Adding another 20% noise to the already modified input vector
# The output SDR should differ considerably from that of the previous output
print "-" * 75 + "入力vectorにさらに20%のノイズを加えた後" + "-" * 75
example.addNoise(0.2)
example.run()



今は入力vectorを少し変えています
1を0に、0を1に少しずつ変えていきます
結果として得られるSDRは、元のSDRと類似していますが、同一ではありません
レッスン - 入力vectorが似ているとSDRが似てくる


---------------------------------------------------------------------------入力vectorに10%のノイズを加えた後---------------------------------------------------------------------------
--------------------------------------------------------------------------------SDRの計算--------------------------------------------------------------------------------
(array([  31,   34,   62,   81,  129,  158,  165,  195,  278,  289,  315,
        347,  448,  481,  817, 1014, 1019, 1022, 1164, 1285, 1361, 1518,
       1583, 1666, 1690, 1693, 1700, 1716, 1734, 1827, 1877, 1931, 2006,
       2009, 2026, 2033, 2049, 2075, 2095, 2111, 2157, 2224, 2334, 2374,
       2384, 2560, 2568, 2613, 2620, 2622, 2723, 2766, 2791, 2799, 2850,
       2859, 2861, 2897, 2963, 3005, 3066, 3074, 3120, 3197, 3247, 3397,
       3432, 3459, 3469, 3492, 3564, 3590, 3621, 3685, 3748, 3792, 3869,
       3906, 3920, 3921, 3955]),)
-